### ISSUE TITLE
PDF Press Next: Update from 2.0.2. to 2.0.3 is endless loop

### ISSUE THREAD

**Issue by creativearc-paul** [dougblackjr/tns-ee-addons#1]
Clicking the 'Update to 2.0.3.' persists every time I click it.

![image](https://github.com/user-attachments/assets/e665d36b-d254-46ec-8c90-b40cbb9d261c)

**Comment by dougblackjr** [comment]
Our first bug and it doesn't even follow our template! I'm ashamed! 🤣 

Thanks for calling this out, we'll take a look.

**Comment by dougblackjr** [comment]
@creativearc-paul This is fixed in version [2.0.4](https://expressionengine.com/add-ons/pdf-press-next)
