### ISSUE TITLE
Live URL and Template Generator Issues

### ISSUE THREAD

**Issue by eric-lamb62** [dougblackjr/tns-ee-addons#2]
When Live URL is installed, template generators won't work right. The field generates this error:

`Unable to load requested fieldtype file: ft.liveurl.php. Confirm the fieldtype file is located in the /system/user/addons/ directory`

The solution is to change the `fieldtypes` array within `addon.setup.php` to use snake case on the name there. Should read like...

```php
    'fieldtypes' => [
        'live_url' => [ //<- that's the change
            'name' => 'LiveUrl',
            'compatibility' => 'text',
        ],
    ],
```

**Comment by dougblackjr** [comment]
Fixed in version [1.1.5](https://expressionengine.com/add-ons/live-url). Thanks for the fix!
