### ISSUE TITLE
PDF Press Next - Spiritix Error

### ISSUE THREAD

**Issue by npuglisi87** [dougblackjr/tns-ee-addons#4]
Generating an issue when using PDF Press Next, I use the code to pull the PDF and get: 
```
Spiritix\Html2Pdf\ConverterException Caught
Shell error: 127
user/addons/pdf_press_next/vendor/spiritix/php-chrome-html2pdf/src/Spiritix/Html2Pdf/Converter.php:192
```

**Describe the bug**
Error thrown upon clicking link to generate pdf. 

**To Reproduce**
1. Click url ({exp:pdf_press_next:save_to_pdf url="{site_url}/test/url/{entry_id}" filename='test.pdf'})

**General Information:**
 - ExpressionEngine Version: 7.5.6
 - Add-on Version: 2.0.4
 - PHP Version: 8.1

**Comment by dougblackjr** [comment]
@npuglisi87 This typically happens if you don't have `exec` or `shell_exec` privileges on your server. Can you confirm if you can run this?

Also that you have npm and node installed, per the README?

**Comment by dougblackjr** [comment]
Closed per Slack
