### ISSUE TITLE
Live Url - base_url issue

### ISSUE THREAD

**Issue by clif-ave** [dougblackjr/tns-ee-addons#5]
HI,

Great product! Ran into an issue for the first time on this site:

The base_url is not parsed. Generates: https://DOMAIN.com/{base_url}/about-us

{site_url} is parsed.

Attached is the cp => settings => Url and Path image

PHP: 8.1.30
EE: 7.5.6

(https://github.com/user-attachments/assets/fd56117e-9dd6-4365-9853-f95d063beaea)
.com/{base_url}/about-us

Thanks!

**Comment by dougblackjr** [comment]
Fixed in version [1.1.6](https://expressionengine.com/add-ons/live-url)
